export interface Card {
  id: number;
  label: string;
  value: string;
  symbol: string;
  image: string;
}

export const CARDS: Card[] = [
  // First set of cards
  { id: 1, label: '2 of Clovers', value: '2', symbol: 'clovers', image: 'Clovers_2.png' },
  { id: 2, label: '3 of Clovers', value: '3', symbol: 'clovers', image: 'Clovers_3.png' },
  { id: 3, label: '4 of Clovers', value: '4', symbol: 'clovers', image: 'Clovers_4.png' },
  { id: 4, label: '5 of Clovers', value: '5', symbol: 'clovers', image: 'Clovers_5.png' },
  { id: 5, label: '6 of Clovers', value: '6', symbol: 'clovers', image: 'Clovers_6.png' },
  { id: 6, label: '7 of Clovers', value: '7', symbol: 'clovers', image: 'Clovers_7.png' },
  { id: 7, label: '8 of Clovers', value: '8', symbol: 'clovers', image: 'Clovers_8.png' },
  { id: 8, label: '9 of Clovers', value: '9', symbol: 'clovers', image: 'Clovers_9.png' },
  { id: 9, label: '10 of Clovers', value: '10', symbol: 'clovers', image: 'Clovers_10.png' },
  { id: 10, label: 'Jack of Clovers', value: '11', symbol: 'clovers', image: 'Clovers_Jack.png' },
  { id: 11, label: 'Queen of Clovers', value: '12', symbol: 'clovers', image: 'Clovers_Queen.png' },
  { id: 12, label: 'King of Clovers', value: '13', symbol: 'clovers', image: 'Clovers_King.png' },
  { id: 13, label: 'Ace of Clovers', value: '1', symbol: 'clovers', image: 'Clovers_A.png' },
  { id: 14, label: '2 of Hearts', value: '2', symbol: 'hearts', image: 'Hearts_2.png' },
  { id: 15, label: '3 of Hearts', value: '3', symbol: 'hearts', image: 'Hearts_3.png' },
  { id: 16, label: '4 of Hearts', value: '4', symbol: 'hearts', image: 'Hearts_4.png' },
  { id: 17, label: '5 of Hearts', value: '5', symbol: 'hearts', image: 'Hearts_5.png' },
  { id: 18, label: '6 of Hearts', value: '6', symbol: 'hearts', image: 'Hearts_6.png' },
  { id: 19, label: '7 of Hearts', value: '7', symbol: 'hearts', image: 'Hearts_7.png' },
  { id: 20, label: '8 of Hearts', value: '8', symbol: 'hearts', image: 'Hearts_8.png' },
  { id: 21, label: '9 of Hearts', value: '9', symbol: 'hearts', image: 'Hearts_9.png' },
  { id: 22, label: '10 of Hearts', value: '10', symbol: 'hearts', image: 'Hearts_10.png' },
  { id: 23, label: 'Jack of Hearts', value: '11', symbol: 'hearts', image: 'Hearts_Jack.png' },
  { id: 24, label: 'Queen of Hearts', value: '12', symbol: 'hearts', image: 'Hearts_Queen.png' },
  { id: 25, label: 'King of Hearts', value: '13', symbol: 'hearts', image: 'Hearts_King.png' },
  { id: 26, label: 'Ace of Hearts', value: '1', symbol: 'hearts', image: 'Hearts_A.png' },
  { id: 27, label: '2 of Tiles', value: '2', symbol: 'tiles', image: 'Tiles_2.png' },
  { id: 28, label: '3 of Tiles', value: '3', symbol: 'tiles', image: 'Tiles_3.png' },
  { id: 29, label: '4 of Tiles', value: '4', symbol: 'tiles', image: 'Tiles_4.png' },
  { id: 30, label: '5 of Tiles', value: '5', symbol: 'tiles', image: 'Tiles_5.png' },
  { id: 31, label: '6 of Tiles', value: '6', symbol: 'tiles', image: 'Tiles_6.png' },
  { id: 32, label: '7 of Tiles', value: '7', symbol: 'tiles', image: 'Tiles_7.png' },
  { id: 33, label: '8 of Tiles', value: '8', symbol: 'tiles', image: 'Tiles_8.png' },
  { id: 34, label: '9 of Tiles', value: '9', symbol: 'tiles', image: 'Tiles_9.png' },
  { id: 35, label: '10 of Tiles', value: '10', symbol: 'tiles', image: 'Tiles_10.png' },
  { id: 36, label: 'Jack of Tiles', value: '11', symbol: 'tiles', image: 'Tiles_Jack.png' },
  { id: 37, label: 'Queen of Tiles', value: '12', symbol: 'tiles', image: 'Tiles_Queen.png' },
  { id: 38, label: 'King of Tiles', value: '13', symbol: 'tiles', image: 'Tiles_King.png' },
  { id: 39, label: 'Ace of Tiles', value: '1', symbol: 'tiles', image: 'Tiles_A.png' },
  { id: 40, label: '2 of Pikes', value: '2', symbol: 'pikes', image: 'Pikes_2.png' },
  { id: 41, label: '3 of Pikes', value: '3', symbol: 'pikes', image: 'Pikes_3.png' },
  { id: 42, label: '4 of Pikes', value: '4', symbol: 'pikes', image: 'Pikes_4.png' },
  { id: 43, label: '5 of Pikes', value: '5', symbol: 'pikes', image: 'Pikes_5.png' },
  { id: 44, label: '6 of Pikes', value: '6', symbol: 'pikes', image: 'Pikes_6.png' },
  { id: 45, label: '7 of Pikes', value: '7', symbol: 'pikes', image: 'Pikes_7.png' },
  { id: 46, label: '8 of Pikes', value: '8', symbol: 'pikes', image: 'Pikes_8.png' },
  { id: 47, label: '9 of Pikes', value: '9', symbol: 'pikes', image: 'Pikes_9.png' },
  { id: 48, label: '10 of Pikes', value: '10', symbol: 'pikes', image: 'Pikes_10.png' },
  { id: 49, label: 'Jack of Pikes', value: '11', symbol: 'pikes', image: 'Pikes_Jack.png' },
  { id: 50, label: 'Queen of Pikes', value: '12', symbol: 'pikes', image: 'Pikes_Queen.png' },
  { id: 51, label: 'King of Pikes', value: '13', symbol: 'pikes', image: 'Pikes_King.png' },
  { id: 52, label: 'Ace of Pikes', value: '1', symbol: 'pikes', image: 'Pikes_A.png' },

  // Second set of cards
  { id: 53, label: '2 of Clovers', value: '2', symbol: 'clovers', image: 'Clovers_2.png' },
  { id: 54, label: '3 of Clovers', value: '3', symbol: 'clovers', image: 'Clovers_3.png' },
  { id: 55, label: '4 of Clovers', value: '4', symbol: 'clovers', image: 'Clovers_4.png' },
  { id: 56, label: '5 of Clovers', value: '5', symbol: 'clovers', image: 'Clovers_5.png' },
  { id: 57, label: '6 of Clovers', value: '6', symbol: 'clovers', image: 'Clovers_6.png' },
  { id: 58, label: '7 of Clovers', value: '7', symbol: 'clovers', image: 'Clovers_7.png' },
  { id: 59, label: '8 of Clovers', value: '8', symbol: 'clovers', image: 'Clovers_8.png' },
  { id: 60, label: '9 of Clovers', value: '9', symbol: 'clovers', image: 'Clovers_9.png' },
  { id: 61, label: '10 of Clovers', value: '10', symbol: 'clovers', image: 'Clovers_10.png' },
  { id: 62, label: 'Jack of Clovers', value: '11', symbol: 'clovers', image: 'Clovers_Jack.png' },
  { id: 63, label: 'Queen of Clovers', value: '12', symbol: 'clovers', image: 'Clovers_Queen.png' },
  { id: 64, label: 'King of Clovers', value: '13', symbol: 'clovers', image: 'Clovers_King.png' },
  { id: 65, label: 'Ace of Clovers', value: '1', symbol: 'clovers', image: 'Clovers_A.png' },
  { id: 66, label: '2 of Hearts', value: '2', symbol: 'hearts', image: 'Hearts_2.png' },
  { id: 67, label: '3 of Hearts', value: '3', symbol: 'hearts', image: 'Hearts_3.png' },
  { id: 68, label: '4 of Hearts', value: '4', symbol: 'hearts', image: 'Hearts_4.png' },
  { id: 69, label: '5 of Hearts', value: '5', symbol: 'hearts', image: 'Hearts_5.png' },
  { id: 70, label: '6 of Hearts', value: '6', symbol: 'hearts', image: 'Hearts_6.png' },
  { id: 71, label: '7 of Hearts', value: '7', symbol: 'hearts', image: 'Hearts_7.png' },
  { id: 72, label: '8 of Hearts', value: '8', symbol: 'hearts', image: 'Hearts_8.png' },
  { id: 73, label: '9 of Hearts', value: '9', symbol: 'hearts', image: 'Hearts_9.png' },
  { id: 74, label: '10 of Hearts', value: '10', symbol: 'hearts', image: 'Hearts_10.png' },
  { id: 75, label: 'Jack of Hearts', value: '11', symbol: 'hearts', image: 'Hearts_Jack.png' },
  { id: 76, label: 'Queen of Hearts', value: '12', symbol: 'hearts', image: 'Hearts_Queen.png' },
  { id: 77, label: 'King of Hearts', value: '13', symbol: 'hearts', image: 'Hearts_King.png' },
  { id: 78, label: 'Ace of Hearts', value: '1', symbol: 'hearts', image: 'Hearts_A.png' },
  { id: 79, label: '2 of Tiles', value: '2', symbol: 'tiles', image: 'Tiles_2.png' },
  { id: 80, label: '3 of Tiles', value: '3', symbol: 'tiles', image: 'Tiles_3.png' },
  { id: 81, label: '4 of Tiles', value: '4', symbol: 'tiles', image: 'Tiles_4.png' },
  { id: 82, label: '5 of Tiles', value: '5', symbol: 'tiles', image: 'Tiles_5.png' },
  { id: 83, label: '6 of Tiles', value: '6', symbol: 'tiles', image: 'Tiles_6.png' },
  { id: 84, label: '7 of Tiles', value: '7', symbol: 'tiles', image: 'Tiles_7.png' },
  { id: 85, label: '8 of Tiles', value: '8', symbol: 'tiles', image: 'Tiles_8.png' },
  { id: 86, label: '9 of Tiles', value: '9', symbol: 'tiles', image: 'Tiles_9.png' },
  { id: 87, label: '10 of Tiles', value: '10', symbol: 'tiles', image: 'Tiles_10.png' },
  { id: 88, label: 'Jack of Tiles', value: '11', symbol: 'tiles', image: 'Tiles_Jack.png' },
  { id: 89, label: 'Queen of Tiles', value: '12', symbol: 'tiles', image: 'Tiles_Queen.png' },
  { id: 90, label: 'King of Tiles', value: '13', symbol: 'tiles', image: 'Tiles_King.png' },
  { id: 91, label: 'Ace of Tiles', value: '1', symbol: 'tiles', image: 'Tiles_A.png' },
  { id: 92, label: '2 of Pikes', value: '2', symbol: 'pikes', image: 'Pikes_2.png' },
  { id: 93, label: '3 of Pikes', value: '3', symbol: 'pikes', image: 'Pikes_3.png' },
  { id: 94, label: '4 of Pikes', value: '4', symbol: 'pikes', image: 'Pikes_4.png' },
  { id: 95, label: '5 of Pikes', value: '5', symbol: 'pikes', image: 'Pikes_5.png' },
  { id: 96, label: '6 of Pikes', value: '6', symbol: 'pikes', image: 'Pikes_6.png' },
  { id: 97, label: '7 of Pikes', value: '7', symbol: 'pikes', image: 'Pikes_7.png' },
  { id: 98, label: '8 of Pikes', value: '8', symbol: 'pikes', image: 'Pikes_8.png' },
  { id: 99, label: '9 of Pikes', value: '9', symbol: 'pikes', image: 'Pikes_9.png' },
  { id: 100, label: '10 of Pikes', value: '10', symbol: 'pikes', image: 'Pikes_10.png' },
  { id: 101, label: 'Jack of Pikes', value: '11', symbol: 'pikes', image: 'Pikes_Jack.png' },
  { id: 102, label: 'Queen of Pikes', value: '12', symbol: 'pikes', image: 'Pikes_Queen.png' },
  { id: 103, label: 'King of Pikes', value: '13', symbol: 'pikes', image: 'Pikes_King.png' },
  { id: 104, label: 'Ace of Pikes', value: '1', symbol: 'pikes', image: 'Pikes_A.png' },
];